import tkinter as tk

win = tk.Tk()
win.title('Bitmaps')
win.iconbitmap('./Tkinter/panda.ico')
win.geometry('280x280')

lb_1 = tk.Label(bitmap = 'error')
lb_1.pack()
lb_2 = tk.Label(bitmap = 'hourglass')
lb_2.pack()
lb_3 = tk.Label(bitmap = 'info')
lb_3.pack()
lb_4 = tk.Label(bitmap = 'questhead')
lb_4.pack()
lb_5 = tk.Label(bitmap = 'question')
lb_5.pack()
lb_6 = tk.Label(bitmap = 'warning')
lb_6.pack()
lb_7 = tk.Label(bitmap = 'gray12')
lb_7.pack()
lb_8 = tk.Label(bitmap = 'gray25')
lb_8.pack()
lb_9 = tk.Label(bitmap = 'gray50')
lb_9.pack()
lb_10 = tk.Label(bitmap = 'gray75')
lb_10.pack()

win.mainloop()
